<?php
require_once 'global.php';

$H_TEMPLATE['TITLE'] = 'Terms & Conditions';
site_header();
?>
<div class="user_content" style="font-weight:normal;">
	<p>
		<small><em>This statement was last updated February 26, 2011.</em></small>
	</p>
	<p>
		The term '<?php echo strtolower(SITE_NAME); ?>' or 'us' or 'we' refers to the owner(s) of 
		the website. The term 'you' refers to the user or viewer of our website. The term 'Content' 
		refers to the website you are using in conjunction with the Service.
	</p>
	<br />
	<div style="margin:5px; border: 1px solid silver; padding: 10px; background-color: #DEDEDE;">
		<h4>Important Summary:</h4>
		<ul>
			<li>Do not advertise <?php echo SITE_NAME; ?> links on any form of traffic exchange / PTC website.</li>
			<li>Do not place <?php echo SITE_NAME; ?> links anywhere that may contain adult material.</li>
			<li>Do not shrink any website URLs that contains adult material.</li>
			<li>Do not ask/beg people to click on an <?php echo SITE_NAME; ?> link simply to generate you revenue, they must want to visit the destination website.</li>
			<li>Do not create 'redirect loops' with similar services to generate revenue.</li>
			<li>Do not create spam with <?php echo SITE_NAME; ?> links anywhere, including forums / chat / comments / blogs.</li>
			<li>Do not participate in click 'rings' where you click on <?php echo SITE_NAME; ?> links in return for others to click yours.</li>
			<li>Do not open <?php echo SITE_NAME; ?> links automatically in any way, including popups / popunders / redirects.</li>
			<li>Only the <?php echo SITE_NAME; ?> link must be opened when clicking on an <?php echo SITE_NAME; ?> link, no other links / windows.</li>
			<li>The only legitimate way to open an <?php echo SITE_NAME; ?> is with a mouse click, on the actual link.</li>
			<li>You may click on your own <?php echo SITE_NAME; ?> links 1 time to test them. You may not create links solely to 'test'.</li>           
		</ul>
		<p><b>If anyone is found or reported breaking any of the rules above or below in the detailed Terms and Conditions, their account will be removed and all earnings forfeited.</b></p>
	</div>
	<br />
	<br />
	<b>1. Acceptance of Terms</b><br />
	Each time you use or cause access to this web site, you agree to be bound by these Terms &amp; Conditions, and as amended from time to time with or without notice to you. In addition, if you are using a particular service on or through this web site, you will be subject to any rules or guidelines applicable to those services and they shall be incorporated by reference into these Terms of Service.<p>
	<b>2. Service Description</b><br />
	<?php echo SITE_NAME; ?> currently provides users with access to a rich collection of resources, including, various communications tools, forums, shopping services, and personalized content its network of properties (the "Service"). You also understand and agree that the Service may include advertisements and that these advertisements are necessary for <?php echo SITE_NAME; ?> to provide the Service. You also understand and agree that the service may include certain communications from <?php echo SITE_NAME; ?>, such as service announcements, administrative messages and the <?php echo SITE_NAME; ?> Newsletter, and that these communications are considered part of <?php echo SITE_NAME; ?> membership and you will not be able to opt out of receiving them. Unless explicitly stated otherwise, any new features that augment or enhance the current Service, including the release of new <?php echo SITE_NAME; ?> properties, shall be subject to the TOS. You understand and agree that the Service is provided "AS-IS" and that <?php echo SITE_NAME; ?> assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.</p><p>
	<b>3. Registration</b><br />
	In consideration of your use of the Service, you represent that you are of legal age to form a binding contract (are at least 18 years old) and are not a person barred from receiving services under the laws of the United Kingdom or other applicable jurisdiction. You also agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Service's registration form (such information being the "Registration Data"), (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete and (c) agree to create only one account per person. If you provide any information that is untrue, inaccurate, not current or incomplete, or <?php echo SITE_NAME; ?> has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, <?php echo SITE_NAME; ?> has the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof).</p><p>
	<b>4. Account Security</b><br />
	You will receive a password and account designation upon completing the Service's registration process. You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your password or account. You agree to immediately notify <?php echo SITE_NAME; ?> of any unauthorized use of your password or account or any other breach of security. <?php echo SITE_NAME; ?> cannot and will not be liable for any loss or damage arising from your failure to comply with this Section 4.</p><p>
	<b>5. User Conduct</b><br />
	You understand that all information, data, text, software, music, sound, photographs, graphics, video, messages or other materials ("Content"), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Content originated. This means that you, and not <?php echo SITE_NAME; ?>, are entirely responsible for all Content that you upload, post, email, transmit or otherwise make available via the Service. <?php echo SITE_NAME; ?> does not control the Content posted via the Service and, as such, does not guarantee the accuracy, integrity or quality of such Content. You understand that by using the Service, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will <?php echo SITE_NAME; ?> be liable in any way for any Content, including, but not limited to, for any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the Service. </p><p>
	You agree to not use the Service to: </p><p>
	</p><ul>
	<li>(a) link to, upload, post, email, transmit or otherwise make available any Content that is adult in nature, unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable; 
	</li><li>(b) harm minors in any way; 
	</li><li>(c) impersonate any person or entity, including, but not limited to, a <?php echo SITE_NAME; ?> official, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity;<br /> 
	</li><li>(d) forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Service;<br /> 
	</li><li>(e) link, upload, post, email, transmit or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);<br /> 
	</li><li>(f) link, upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights ("Rights") of any party;<br /> 
	</li><li>(g) link, upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation, except in those areas (such as shopping rooms) that are designated for such purpose (please read our complete Spam Policy);<br /> 
	</li><li>(h) link, upload, post, email, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;<br /> 
	</li><li>(i) disrupt the normal flow of dialogue, cause a screen to "scroll" faster than other users of the Service are able to type, or otherwise act in a manner that negatively affects other users' ability to engage in real time exchanges;<br /> 
	</li><li>(j) interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service;<br /> 
	</li><li>(k) intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law;<br /> 
	</li><li>(l) "stalk" or otherwise harass another; or<br /> 
	</li><li>(m) collect or store personal data about other users.<br />
	</li><li>(n) attempt to falsify traffic in order to earn revenue, not limited to using automated 'computer' traffic, disguising traffic through anonymous proxy servers, 'hiding' the Service through any method.<br />
	</li><li>(o) register more than one account per person, except when one is a Publisher account and one is an Advertiser account. If a publisher is found to have referred themselves, the referral commission will be forfeited.<br />
	</li><li>(p) offer any form of incentive to users who click on an <?php echo SITE_NAME; ?> link, not limited to points/bonus/money/gifts/traffic or link exchange.<br />
	</li></ul>
	<p> 
	You acknowledge that <?php echo SITE_NAME; ?> may OR MAY NOT pre-screen Content, but that <?php echo SITE_NAME; ?> and its designees shall have the right (but not the obligation) in their sole discretion to PRE-SCREEN, refuse, or move any Content (or Account) that is available via the Service. Without limiting the foregoing, <?php echo SITE_NAME; ?> and its designees shall have the right to remove any Content or Accounts that violates the TOS or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content or Accounts, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Content or Accounts created by <?php echo SITE_NAME; ?> or submitted to <?php echo SITE_NAME; ?>, including without limitation information in <?php echo SITE_NAME; ?> message boards, and in all other parts of the Service.</p><p> 
	You acknowledge, consent and agree that <?php echo SITE_NAME; ?> may access, preserve, and disclose your account information and Content if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the TOS; (c) respond to claims that any Content violates the rights of third-parties; (d) respond to your requests for customer service; or (e) protect the rights, property, or personal safety of <?php echo SITE_NAME; ?>, its users and the public.</p><p>
	You understand that the technical processing and transmission of the Service, including your Content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p><p> 
	You understand that the Service and software embodied within the Service may include security components that permit digital materials to be protected, and use of these materials is subject to usage rules set by <?php echo SITE_NAME; ?> and/or content providers who provide content to the Service. You may not attempt to override or circumvent any of the usage rules embedded into the Service. Any unauthorized reproduction, publication, further distribution or public exhibition of the materials provided on the Service, in whole or in part, is strictly prohibited.</p><p>
	<b>6. Submitted Content</b><br />
	<?php echo SITE_NAME; ?> does not claim ownership of Content you submit or make available for inclusion on the Service. However, with respect to Content you submit or make available for inclusion on publicly accessible areas of the Service, you grant <?php echo SITE_NAME; ?> the following world-wide, royalty free and non-exclusive license(s), as applicable: </p><p>
	 - With respect to Content you submit or make available for inclusion on publicly accessible areas of <?php echo SITE_NAME; ?>, the license to use, distribute, reproduce, modify, adapt, publicly perform and publicly display such Content on the Service solely for the purposes of providing and promoting the specific Service which such Content was submitted or made available. This license exists only for as long as you elect to continue to include such Content on the Service and will terminate at the time you remove or <?php echo SITE_NAME; ?> removes such Content from the Service. </p><p>
	 - With respect to photos, graphics, audio or video you submit or make available for inclusion on publicly accessible area of the Service, the license to use, distribute, reproduce, modify, adapt, publicly perform and publicly display such Content on the Service solely for the purpose for which such Content was submitted or made available. This license exists only for as long as you elect to continue to include such Content on the Service and will terminate at the time you remove or <?php echo SITE_NAME; ?> removes such Content from the Service. </p><p>
	 - With respect to Content other than photos, graphics, audio or video you submit or make available for inclusion on publicly accessible areas of the Service, the perpetual, irrevocable and fully sublicensable license to use, distribute, reproduce, modify, adapt, publish, translate, publicly perform and publicly display such Content (in whole or in part) and to incorporate such Content into other works in any format or medium now known or later developed. </p><p>
	"Publicly accessible" areas of the Service are those areas of <?php echo SITE_NAME; ?> that are intended by <?php echo SITE_NAME; ?> to be available to the general public. By way of example, publicly accessible areas of the Service would include <?php echo SITE_NAME; ?> news and resources that are open to both members and visitors. However, publicly accessible areas of the Service would not include portions of <?php echo SITE_NAME; ?> that are limited to members, <?php echo SITE_NAME; ?> services intended for private communication such as private messages, or areas off of <?php echo SITE_NAME; ?> such as portions of World Wide Web sites that are accessible through via hypertext or other links but are not hosted or served by <?php echo SITE_NAME; ?>.</p><p>			
	<b>7. Payment</b><br />
	Payments from <?php echo SITE_NAME; ?> are made through PayPal (http://www.paypal.com) on first Monday of every Month. The minimum amount available for a withdrawal is USD$5.00 if the registration of the account was after 1st July 2009 or a previous withdrawal has already been processed. Otherwise the minimum withdrawal is USD$20.00.</p><p>
	<b>8. Earnings</b><br />
	<?php echo SITE_NAME; ?> will pay you, the Publisher, 50% of the revenue generated through advertisments displayed on the Service associated with your Account.</p><p>
	<b>9. Defaults</b><br />
	If there are no advertisers on the Service for your traffic demographics then a 'default' advertisement will be shown. You may change the 'default' advertisement under the Account section of the website. Default advertisements are not paid for by <?php echo SITE_NAME; ?>.
	</p><p>
	<b>10. Service URLs</b><br />
	<?php echo SITE_NAME; ?> reserve the right to remove any 'URLs' associated with your account if they do not receive at least 3 unique visitors in a 3 month period.
	</p><p>    
	<b>11. Indemnity</b><br />
	You agree to indemnify and hold <?php echo SITE_NAME; ?>, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of Content you submit, post, transmit or make available through the Service, your use of the Service, your connection to the Service, your violation of the TOS, or your violation of any rights of another.</p><p>
	<b>12. No resale of Service</b><br />
	You agree not to reproduce, duplicate, copy, sell, trade, resell or exploit for any commercial purposes, any portion of the Service (including your <?php echo SITE_NAME; ?> I.D.), use of the Service, or access to the Service.</p><p>
	<b>13. Modification of Service</b><br />
	<?php echo SITE_NAME; ?> reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that <?php echo SITE_NAME; ?> shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p><p>
	<b>14. Termination</b><br />
	You agree that <?php echo SITE_NAME; ?> may, under certain circumstances and without prior notice, immediately terminate your <?php echo SITE_NAME; ?> account and access to the Service. Cause for such termination shall include, but not be limited to, (a) breaches or violations of the TOS or other incorporated agreements or guidelines, (b) requests by law enforcement or other government agencies, (c) a request by you (self-initiated account deletions), (d) discontinuance or material modification to the Service (or any part thereof), (e) unexpected technical or security issues or problems, and (f) extended periods of inactivity. Termination of your <?php echo SITE_NAME; ?> account includes (a) removal of access to all offerings within the Service, including but not limited to <?php echo SITE_NAME; ?> message boards, (b) deletion of your password and all related information, files and content associated with or inside your account (or any part thereof), and (c) barring further use of the Service. Further, you agree that all terminations for cause shall be made in <?php echo SITE_NAME; ?>' sole discretion and that <?php echo SITE_NAME; ?> shall not be liable to you or any third-party for any termination of your account, any associated email address, or access to the Service.</p><p>
	<b>15. Disclaimer of Warranties</b><br />
	YOU EXPRESSLY UNDERSTAND AND AGREE THAT: </p><p>
	1. YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. <?php echo SITE_NAME; ?> EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.<br /> 
	2. <?php echo SITE_NAME; ?> MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED. <br />
	3. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.<br /> 
	4. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM <?php echo SITE_NAME; ?> OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS. <br />
	5. A SMALL PERCENTAGE OF USERS MAY EXPERIENCE EPILEPTIC SEIZURES WHEN EXPOSED TO CERTAIN LIGHT PATTERNS OR BACKGROUNDS ON A COMPUTER SCREEN OR WHILE USING THE SERVICE. CERTAIN CONDITIONS MAY INDUCE PREVIOUSLY UNDETECTED EPILEPTIC SYMPTOMS EVEN IN USERS WHO HAVE NO HISTORY OF PRIOR SEIZURES OR EPILEPSY. IF YOU, OR ANYONE IN YOUR FAMILY, HAVE AN EPILEPTIC CONDITION, CONSULT YOUR PHYSICIAN PRIOR TO USING THE SERVICE. IMMEDIATELY DISCONTINUE USE OF THE SERVICE AND CONSULT YOUR PHYSICIAN IF YOU EXPERIENCE ANY OF THE FOLLOWING SYMPTOMS WHILE USING THE SERVICE -- DIZZINESS, ALTERED VISION, EYE OR MUSCLE TWITCHES, LOSS OF AWARENESS, DISORIENTATION, ANY INVOLUNTARY MOVEMENT, OR CONVULSIONS.</p><p>
	<b>16. Limitaion of Liability</b><br />
	YOU EXPRESSLY UNDERSTAND AND AGREE THAT <?php echo SITE_NAME; ?> SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF <?php echo SITE_NAME; ?> HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE.</p><p>
	<b>17. Violations</b><br />
	Please report any violations of these Terms &amp; Conditions to the <a href="contact.php">contact form</a>.
	</p>
</div>
<?php site_footer(); ?>